services:
  - type: web
    name: sukie-mangas-api # Ou o nome que preferir
    runtime: node
    plan: starter # IMPORTANTE: O plano gratuito pode não ter RAM suficiente. "Starter" é mais seguro.
    buildCommand: "npm install && npx playwright install --with-deps chromium"
    startCommand: "node server.js"
    healthCheckPath: /popular
    envVars:
      - key: NODE_ENV
        value: production
      # Opcional, mas boa prática: especifica onde o Playwright deve ser armazenado para builds mais rápidos no futuro
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/playwright